In [145]:
import pandas as pd
import numpy as np

In [146]:
data_may_04_19 = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_190504.txt")
data_may_11_19 = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_190511.txt")
#data_may_18_19 = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_190518.txt")
#data_may_25_19 = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_190525.txt")
#data_may_05_18 = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_180505.txt")
#data_may_12_18 = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_180512.txt")
#data_may_19_18 = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_180519.txt")
#data_may_26_18 = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_180526.txt")

In [147]:
all_data = pd.concat([data_may_04_19, data_may_11_19], ignore_index=True)
#all_data = pd.concat([data_may_04_19, data_may_11_19, data_may_18_19, data_may_25_19, data_may_05_18, data_may_12_18, data_may_19_18, data_may_26_18])
all_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 410945 entries, 0 to 410944
Data columns (total 11 columns):
 #   Column                                                                Non-Null Count   Dtype
---  ------                                                                --------------   -----
 0   C/A                                                                   410945 non-null  object
 1   UNIT                                                                  410945 non-null  object
 2   SCP                                                                   410945 non-null  object
 3   STATION                                                               410945 non-null  object
 4   LINENAME                                                              410945 non-null  object
 5   DIVISION                                                              410945 non-null  object
 6   DATE                                                                  410945 non-null  object
 7   TIME                                                                  410945 non-null  object
 8   DESC                                                                  410945 non-null  object
 9   ENTRIES                                                               410945 non-null  int64
 10  EXITS                                                                 410945 non-null  int64
dtypes: int64(2), object(9)
memory usage: 34.5+ MB

In [148]:
all_data['datetime'] = pd.to_datetime(all_data['DATE'] + ' ' + all_data['TIME'])

In [149]:
all_data['turnstile'] = all_data['C/A'] + all_data['UNIT'] + all_data['SCP'] + all_data['STATION']

In [150]:
all_data.sort_values(by = ['turnstile', 'datetime'], inplace = True)

In [151]:
all_data.tail(50)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,datetime,turnstile
206849,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/02/2019,17:00:00,REGULAR,5554,376,2019-05-02 17:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
206850,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/02/2019,21:00:00,REGULAR,5554,376,2019-05-02 21:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
206851,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/03/2019,01:00:00,REGULAR,5554,376,2019-05-03 01:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
206852,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/03/2019,05:00:00,REGULAR,5554,376,2019-05-03 05:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
206853,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/03/2019,09:00:00,REGULAR,5554,376,2019-05-03 09:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
206854,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/03/2019,13:00:00,REGULAR,5554,376,2019-05-03 13:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
206855,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/03/2019,17:00:00,REGULAR,5554,376,2019-05-03 17:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
206856,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/03/2019,21:00:00,REGULAR,5554,376,2019-05-03 21:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410903,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/04/2019,01:00:00,REGULAR,5554,376,2019-05-04 01:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410904,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/04/2019,05:00:00,REGULAR,5554,376,2019-05-04 05:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410905,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/04/2019,09:00:00,REGULAR,5554,376,2019-05-04 09:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410906,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/04/2019,13:00:00,REGULAR,5554,376,2019-05-04 13:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410907,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/04/2019,17:00:00,REGULAR,5554,376,2019-05-04 17:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410908,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/04/2019,21:00:00,REGULAR,5554,376,2019-05-04 21:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410909,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/05/2019,01:00:00,REGULAR,5554,376,2019-05-05 01:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410910,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/05/2019,05:00:00,REGULAR,5554,376,2019-05-05 05:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410911,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/05/2019,09:00:00,REGULAR,5554,376,2019-05-05 09:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410912,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/05/2019,13:00:00,REGULAR,5554,376,2019-05-05 13:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410913,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/05/2019,17:00:00,REGULAR,5554,376,2019-05-05 17:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410914,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/05/2019,21:00:00,REGULAR,5554,376,2019-05-05 21:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410915,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/06/2019,01:00:00,REGULAR,5554,376,2019-05-06 01:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410916,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/06/2019,05:00:00,REGULAR,5554,376,2019-05-06 05:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410917,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/06/2019,09:00:00,REGULAR,5554,376,2019-05-06 09:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410918,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/06/2019,13:00:00,REGULAR,5554,376,2019-05-06 13:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410919,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/06/2019,17:00:00,REGULAR,5554,376,2019-05-06 17:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410920,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/06/2019,21:00:00,REGULAR,5554,376,2019-05-06 21:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410921,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/07/2019,01:00:00,REGULAR,5554,376,2019-05-07 01:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410922,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/07/2019,05:00:00,REGULAR,5554,376,2019-05-07 05:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410923,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/07/2019,09:00:00,REGULAR,5554,376,2019-05-07 09:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410924,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/07/2019,13:00:00,REGULAR,5554,376,2019-05-07 13:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410925,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/07/2019,17:00:00,REGULAR,5554,376,2019-05-07 17:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410926,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/07/2019,21:00:00,REGULAR,5554,376,2019-05-07 21:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410927,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/08/2019,01:00:00,REGULAR,5554,376,2019-05-08 01:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410928,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/08/2019,05:00:00,REGULAR,5554,376,2019-05-08 05:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410929,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/08/2019,09:00:00,REGULAR,5554,376,2019-05-08 09:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410930,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/08/2019,13:00:00,REGULAR,5554,376,2019-05-08 13:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410931,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/08/2019,17:00:00,REGULAR,5554,376,2019-05-08 17:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410932,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/08/2019,21:00:00,REGULAR,5554,376,2019-05-08 21:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410933,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/09/2019,01:00:00,REGULAR,5554,376,2019-05-09 01:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410934,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/09/2019,05:00:00,REGULAR,5554,376,2019-05-09 05:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410935,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/09/2019,09:00:00,REGULAR,5554,376,2019-05-09 09:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410936,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/09/2019,13:00:00,REGULAR,5554,376,2019-05-09 13:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410937,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/09/2019,17:00:00,REGULAR,5554,376,2019-05-09 17:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410938,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/09/2019,21:00:00,REGULAR,5554,376,2019-05-09 21:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410939,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/10/2019,01:00:00,REGULAR,5554,376,2019-05-10 01:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410940,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/10/2019,05:00:00,REGULAR,5554,376,2019-05-10 05:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410941,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/10/2019,09:00:00,REGULAR,5554,376,2019-05-10 09:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410942,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/10/2019,13:00:00,REGULAR,5554,376,2019-05-10 13:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410943,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/10/2019,17:00:00,REGULAR,5554,376,2019-05-10 17:00:00,TRAM2R46900-05-01RIT-ROOSEVELT
410944,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/10/2019,21:00:00,REGULAR,5554,376,2019-05-10 21:00:00,TRAM2R46900-05-01RIT-ROOSEVELT

In [169]:
#all_data['first_datetime'] = all_data.groupby('turnstile').min('datetime')

# I used 'First' as fillna so it would be easier to see how many it would change, will sub in 0 later
all_data['entries_diff'] = all_data.groupby('turnstile')['ENTRIES'].diff()
#all_data.sort_values(['entries_diff'], ascending = False).head(20)
#all_data.sort_values(['turnstile', 'datetime'])
#all_data.iloc[143675:143700]
#all_data[all_data['turnstile'] == 'N196R28500-05-01FAR ROCKAWAY']
#all_data[all_data['datetime'] == '2019-05-03 16:00:00']

#all_data.reset_index(inplace = True)

#all_data['daily_entries']

all_data.groupby(['turnstile','DATE']).sum('entries_diff')

                                             index   ENTRIES  \
turnstile                      DATE
A002R05102-00-0059 ST          04/27/2019       15  42212783
                               04/28/2019       51  42217534
                               04/29/2019       87  42222537
                               04/30/2019      123  42231580
                               05/01/2019      159  42240617
...                                            ...       ...
TRAM2R46900-05-01RIT-ROOSEVELT 05/06/2019  2465505     33324
                               05/07/2019  2465541     33324
                               05/08/2019  2465577     33324
                               05/09/2019  2465613     33324
                               05/10/2019  2465649     33324

                                           EXITS                                                                 \
turnstile                      DATE
A002R05102-00-0059 ST          04/27/2019                                           14309589
                               04/28/2019                                           14310871
                               04/29/2019                                           14312896
                               04/30/2019                                           14315824
                               05/01/2019                                           14318596
...                                                                                      ...
TRAM2R46900-05-01RIT-ROOSEVELT 05/06/2019                                               2256
                               05/07/2019                                               2256
                               05/08/2019                                               2256
                               05/09/2019                                               2256
                               05/10/2019                                               2256

                                           entries_diff
turnstile                      DATE
A002R05102-00-0059 ST          04/27/2019         681.0
                               04/28/2019         691.0
                               04/29/2019        1421.0
                               04/30/2019        1478.0
                               05/01/2019        1555.0
...                                                 ...
TRAM2R46900-05-01RIT-ROOSEVELT 05/06/2019           0.0
                               05/07/2019           0.0
                               05/08/2019           0.0
                               05/09/2019           0.0
                               05/10/2019           0.0

[67690 rows x 4 columns]

In [128]:
# check to see if number of distinct turnstiles matches the number that were filled in as 'First'
all_data['turnstile'].nunique()
# Number of distinct turnstiles matches number of 'First' entries

4853

In [171]:
all_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 410945 entries, 0 to 410944
Data columns (total 15 columns):
 #   Column                                                                Non-Null Count   Dtype
---  ------                                                                --------------   -----
 0   index                                                                 410945 non-null  int64
 1   C/A                                                                   410945 non-null  object
 2   UNIT                                                                  410945 non-null  object
 3   SCP                                                                   410945 non-null  object
 4   STATION                                                               410945 non-null  object
 5   LINENAME                                                              410945 non-null  object
 6   DIVISION                                                              410945 non-null  object
 7   DATE                                                                  410945 non-null  object
 8   TIME                                                                  410945 non-null  object
 9   DESC                                                                  410945 non-null  object
 10  ENTRIES                                                               410945 non-null  int64
 11  EXITS                                                                 410945 non-null  int64
 12  datetime                                                              410945 non-null  datetime64[ns]
 13  turnstile                                                             410945 non-null  object
 14  entries_diff                                                          406092 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(3), object(10)
memory usage: 47.0+ MB

In [166]:
all_data[all_data['datetime'] == '2019-05-03 16:00:00']

,index,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,datetime,turnstile,entries_diff
42,42,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2019,16:00:00,REGULAR,7043403,2387631,2019-05-03 16:00:00,A002R05102-00-0059 ST,354.0
128,86,A002,R051,02-00-01,59 ST,NQR456W,BMT,05/03/2019,16:00:00,REGULAR,6274905,1407361,2019-05-03 16:00:00,A002R05102-00-0159 ST,257.0
214,130,A002,R051,02-03-00,59 ST,NQR456W,BMT,05/03/2019,16:00:00,REGULAR,1227185,4614921,2019-05-03 16:00:00,A002R05102-03-0059 ST,114.0
300,174,A002,R051,02-03-01,59 ST,NQR456W,BMT,05/03/2019,16:00:00,REGULAR,1089998,1682197,2019-05-03 16:00:00,A002R05102-03-0159 ST,316.0
386,218,A002,R051,02-03-02,59 ST,NQR456W,BMT,05/03/2019,16:00:00,REGULAR,6174151,8325268,2019-05-03 16:00:00,A002R05102-03-0259 ST,291.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409056,205362,S101,R070,00-00-08,ST. GEORGE,1,SRT,05/03/2019,16:00:00,REGULAR,2332483,9196,2019-05-03 16:00:00,S101R07000-00-08ST. GEORGE,32.0
409156,205417,S101,R070,00-03-00,ST. GEORGE,1,SRT,05/03/2019,16:00:00,REGULAR,4745077,4495,2019-05-03 16:00:00,S101R07000-03-00ST. GEORGE,112.0
409256,205472,S101,R070,00-03-01,ST. GEORGE,1,SRT,05/03/2019,16:00:00,REGULAR,1545817,101,2019-05-03 16:00:00,S101R07000-03-01ST. GEORGE,88.0
409356,205527,S101,R070,00-03-02,ST. GEORGE,1,SRT,05/03/2019,16:00:00,REGULAR,1494011,100,2019-05-03 16:00:00,S101R07000-03-02ST. GEORGE,85.0
409456,205582,S101,R070,00-03-03,ST. GEORGE,1,SRT,05/03/2019,16:00:00,REGULAR,1698202,260,2019-05-03 16:00:00,S101R07000-03-03ST. GEORGE,111.0

In [170]:
all_data['DESC'].unique()

array(['REGULAR', 'RECOVR AUD'], dtype=object)